---

- name: "normalize | build_empty_data"
  ansible.builtin.set_fact:
    _norm_empty_data:
      system:   null
      hardware: null
      bmc:      null
      cpu:      null
      memory:   null
      storage:
        filesystems:     []
        physical_disks:  []
        datastores:      []
        controllers:     []
        logical_volumes: []
        hbas:            []
        infiniband:      []
        summary:
          groups:         []
          grand_total_gb: 0
      network:
        dns_servers:      []
        default_gateways: []
        interfaces:       []
        adapters:         []
        ports:            []
        virtual_switches: []
        portgroups:       []
        driver_map:       []
        summary:
          groups: []
      users:    []
      firmware: []
      power:    null
      thermal:
        temperatures: []
        fans:         []
  no_log: true
