---

- name: "normalize | build_correlation"
  ansible.builtin.set_fact:
    _correlation:
      serial_number: >-
        {{ (_merged_data.hardware.serial | default(none))
           if _merged_data.hardware is defined and _merged_data.hardware is mapping
           else (_merged_data.system.serial_number | default(none))
           if _merged_data.system is mapping
           else none }}
      system_uuid: >-
        {{ ((_merged_data.hardware.uuid | default(none))
           if _merged_data.hardware is defined and _merged_data.hardware is mapping
           else (_merged_data.system.system_uuid | default(none))
           if _merged_data.system is defined and _merged_data.system is mapping
           else none) | normalize_uuid }}
      bmc_ip: >-
        {{ (_merged_data.bmc.ip | default(none))
           if _merged_data.bmc is defined and _merged_data.bmc is mapping
           else none }}
      host_ip: "{{ _out_ip | default(none) }}"
