---

- name: "normalize | build_status"
  ansible.builtin.set_fact:
    _out_status: >-
      {%- set sec_vals = _norm_sections.values() | list -%}
      {%- set supported_vals = sec_vals | reject('equalto','not_supported') | list -%}
      {%- set success_count  = supported_vals | select('equalto','success') | list | length -%}
      {%- set failed_count   = supported_vals | select('equalto','failed')  | list | length -%}
      {%- if supported_vals | length == 0 -%}
      failed
      {%- elif failed_count == 0 -%}
      success
      {%- elif success_count == 0 -%}
      failed
      {%- else -%}
      partial
      {%- endif -%}
