"""`prodgen promote` / `prodgen restore` via git plumbing (dry-run capable).

promote: build(sha) -> gates -> blobs (hash-object -w --no-filters) -> temp index
         (read-tree --empty + update-index --index-info) -> write-tree -> commit-tree with
         trailers -> update-ref (compare-and-swap on the previous production SHA) -> push.
restore: new commit whose tree is a previous production commit's tree (no history rewrite).
Dry-run computes blob/tree ids without writing objects (write-tree --missing-ok).
"""
from __future__ import annotations

import datetime
import json
import os
import tempfile

from . import GENERATOR_VERSION, PROVENANCE_FILE, RULES_VERSION
from .build import build
from .common import ProdgenError
from .gitstore import GitStore
from .verify import run_gates


def _now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()


def _message(title: str, body: str, trailers: dict) -> str:
    lines = [title, "", body, ""]
    lines += [f"{k}: {v}" for k, v in trailers.items()]
    return "\n".join(lines) + "\n"


def promote(repo_root: str, sha: str, manifest_path: str, *, dry_run: bool = True, ci_build: str = "",
            production_ref: str = "refs/heads/production", push_remote: str = "", skip_live: bool = True) -> dict:
    store = GitStore(repo_root)
    main_sha = store.rev_parse(sha)
    result = {"main_sha": main_sha, "dry_run": dry_run, "production_ref": production_ref, "ok": False}
    with tempfile.TemporaryDirectory(prefix="prodgen-promote-") as td:
        out = os.path.join(td, "tree")
        report = build(repo_root, main_sha, out, manifest_path, live_checkers=True)
        result["build"] = {"ok": report.ok, "files": report.file_count, "bytes": report.total_bytes,
                           "tree_hash": report.tree_hash,
                           "class_b": [{"path": p, "line": l, "reason": r} for p, l, r in report.class_b]}
        if not report.ok:
            result["stage"] = "build"
            return result
        gates = run_gates(repo_root, out, manifest_path, skip_live=skip_live)
        result["gates"] = {"ok": gates.ok, "results": [(r.id, r.status) for r in gates.results]}
        if not gates.ok:
            result["stage"] = "verify"
            result["gate_details"] = [(r.id, r.details[:5]) for r in gates.results if r.status == "FAIL"]
            return result
        with open(os.path.join(out, PROVENANCE_FILE), "rb") as fh:
            prov_bytes = fh.read()
        prov = json.loads(prov_bytes.decode("utf-8"))
        # dry-run: objects go to a scratch object directory (real store read-only via alternates)
        env = store.isolated_object_env(os.path.join(td, "objects")) if dry_run else None
        if dry_run:
            os.makedirs(os.path.join(td, "objects"), exist_ok=True)
        files = []
        for rel, rec in sorted(prov["files"].items()):
            with open(os.path.join(out, *rel.split("/")), "rb") as fh:
                data = fh.read()
            files.append((rec["mode"], store.hash_object(data, write=True, env=env), rel))
        files.append(("100644", store.hash_object(prov_bytes, write=True, env=env), PROVENANCE_FILE))
        tree = store.build_tree(files, write=True, env=env)
    prev = store.rev_parse(production_ref) if store.rev_exists(production_ref) else None
    trailers = {
        "Main-SHA": main_sha,
        "Tree-Hash": prov["tree_hash"],
        "Generator-Version": GENERATOR_VERSION,
        "Rules-Version": RULES_VERSION,
        "Previous-Production": prev or "none",
        "CI-Build": ci_build or "manual",
        "Generated-At": _now(),
    }
    message = _message(f"production: runtime tree from main {main_sha[:12]}",
                       "Generated by prodgen from a fixed main SHA (object store only); comments stripped,\n"
                       "gates G01-G17 passed as recorded in .production-provenance.json.", trailers)
    result.update({"tree": tree, "parent": prev, "message": message, "files": len(files), "stage": "commit"})
    if dry_run:
        result["ok"] = True
        result["note"] = "dry-run: no objects written, no ref updated"
        return result
    commit = store.commit_tree(tree, [prev] if prev else [], message)
    store.update_ref(production_ref, commit, prev)
    result["commit"] = commit
    if push_remote:
        store.run(["push", push_remote, f"{production_ref}:{production_ref}"])
        result["pushed"] = push_remote
    result["ok"] = True
    return result


def restore(repo_root: str, to_commit: str, *, dry_run: bool = True, production_ref: str = "refs/heads/production",
            push_remote: str = "") -> dict:
    store = GitStore(repo_root)
    target = store.rev_parse(to_commit)
    target_tree = store.commit_tree_sha(target)
    prov_bytes = store.cat_path(target, PROVENANCE_FILE)
    if prov_bytes is None:
        raise ProdgenError(f"{to_commit} carries no {PROVENANCE_FILE}; refusing to restore a non-prodgen tree")
    prov = json.loads(prov_bytes.decode("utf-8"))
    prev = store.rev_parse(production_ref) if store.rev_exists(production_ref) else None
    result = {"target": target, "target_tree": target_tree, "parent": prev, "dry_run": dry_run,
              "production_ref": production_ref, "ok": False}
    if prev == target:
        result.update({"ok": True, "note": "production already points at the target"})
        return result
    trailers = {
        "Restore-Of": target,
        "Main-SHA": prov.get("main_sha", "unknown"),
        "Tree-Hash": prov.get("tree_hash", "unknown"),
        "Generator-Version": prov.get("generator_version", "unknown"),
        "Rules-Version": prov.get("rules_version", "unknown"),
        "Previous-Production": prev or "none",
        "Generated-At": _now(),
    }
    message = _message(f"production: restore tree of {target[:12]}",
                       "Restores a previous production tree as a new commit (no history rewrite).", trailers)
    result["message"] = message
    if dry_run:
        result["ok"] = True
        result["note"] = "dry-run: no ref updated"
        return result
    commit = store.commit_tree(target_tree, [prev] if prev else [], message)
    store.update_ref(production_ref, commit, prev)
    result["commit"] = commit
    if push_remote:
        store.run(["push", push_remote, f"{production_ref}:{production_ref}"])
        result["pushed"] = push_remote
    result["ok"] = True
    return result
