"""Golden fixtures: tests/fixtures/prodgen/<name> -> <name>.expected.<ext>.

The expected files were generated by prodgen and reviewed by hand; a change in output means a
deliberate rule change (regenerate and re-review) or a regression.
"""
import pytest

from scripts.ai.prodgen.common import PathMatcher
from scripts.ai.prodgen.manifest import IncludeEntry
from scripts.ai.prodgen.strip import StripContext, psstrip, residual_scan, strip_file

CASES = [
    ("sample_tasks.yml", "sample_tasks.expected.yml", "yaml", None, True),
    ("sample_module.py", "sample_module.expected.py", "python", "library", False),
    ("sample.groovy", "sample.expected.groovy", "groovy", None, False),
    ("sample.sh", "sample.expected.sh", "shell", None, False),
    ("sample.cfg", "sample.expected.cfg", "ini", None, False),
]


@pytest.mark.parametrize("src,expected,language,kind,needs_ps", CASES)
def test_golden(fixtures_dir, src, expected, language, kind, needs_ps):
    ctx = StripContext(policy={"jinja_trim_blocks": "ansible", "powershell_strip": True})
    if needs_ps:
        parser = psstrip.PowerShellParser()
        if not parser.available:
            pytest.skip("golden with PowerShell block needs a PowerShell parser")
        ctx.ps_parser = parser
    data = (fixtures_dir / src).read_bytes()
    assert b"\r" not in data
    entry = IncludeEntry(pattern=src, language=language, mode="100644", python_kind=kind, matcher=PathMatcher([src]))
    res = strip_file(language, data, src, entry, ctx)
    assert not res.class_b, res.class_b
    assert res.output == (fixtures_dir / expected).read_text(encoding="utf-8")
    # nothing comment-like remains except class-A rules
    leftovers = [(ln, rule) for ln, rule in residual_scan(language, res.output.encode("utf-8"), src, entry, ctx) if rule is None]
    assert leftovers == []


def test_golden_inputs_are_lf_and_end_with_newline(fixtures_dir):
    for name in sorted(p.name for p in fixtures_dir.iterdir()):
        data = (fixtures_dir / name).read_bytes()
        assert b"\r" not in data, name
        assert data.endswith(b"\n"), name
