#!/usr/bin/env python3
"""build_functions.py — Jenkinsfile_portal 의 최상위 함수들을 떼어 Harness 용 Groovy 스크립트를 만든다 (2026-10-04, Astra 3차 §5-2).

운영 코드에는 장애 주입 분기를 넣지 않는다. 대신 이 도구가
  1. Jenkinsfile_portal(main checkout 또는 생성 tree 의 사본) 에서 `pipeline {` 앞의 최상위 선언(상수·helper·seFinalizeAndCallback·
     sePreserveGatherOutput …)을 **그대로** 잘라내고,
  2. 같은 이름의 **wrapper 메서드**(archiveArtifacts · stash · unstash · unarchive · readTrusted · readFile · sh · unstable · httpRequest,
     9차 gather_stage: node · nodesByLabel · retry · ws · checkout · withCredentials) 와
     `getParams()`(params 그림자) 를 덧붙여 — 스크립트 메서드가 DSL step 보다 먼저 해석되므로 시나리오별로 실제 step 에 위임하거나
     예외·지연을 일으킨다 —
  3. `return this` 로 끝나는 파일을 만든다. Jenkinsfile_harness 가 `load` 한 뒤 `seHarnessInit(this, cfg)` 로 바깥 스크립트(실제 step)를 넘긴다.

원본 함수 본문은 글자 하나 바꾸지 않는다 — 출력의 `source_sha256`(원본 파일 해시)과 `functions_sha256`(잘라낸 부분 해시)를 기록해
어느 생성물의 함수를 검증했는지 남긴다 (wrapper 를 붙이기 전 해시).

사용:
  python3 tests/jenkins/harness/build_functions.py --source Jenkinsfile_portal --scenario archive_fail \
      --out harness_functions.groovy --meta harness_functions_meta.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


def _write_lf(path, text):
    """LF 고정 쓰기 — Path.write_text(newline=) 는 Python 3.10+ 라 Runner 시스템 python3(3.9) 에서 못 쓴다."""
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

FAIL_ARCHIVE = {"archive_fail", "both_fail"}
FAIL_STASH = {"stash_fail", "both_fail"}
FAIL_LAYER_A = {"layer_a_fail", "checkpoint_only_b"}
FAIL_READTRUSTED = {"raw_fallback"}
SLOW_UNSTASH = {"recover_slow", "outer_timeout", "user_abort"}
FOREIGN_TIMEOUT_UNSTASH = {"foreign_timeout_interruption"}    # unstash 안에서 **다른** timeout 으로 FIE 를 만든다 (3차 §4 ⑥)
# 2026-10-04 최종 지시 §4-3 — 느린 보존 archive / 결과 확인 단계의 정리 결과 읽기(readFile gather_final.jsonl). 8차 R3: 안쪽 상한이 없어 기다려 완주한다
SLOW_ARCHIVE = {"archive_slow"}
SLOW_READFILE_FINAL = {"layer_a_read_slow"}
# 결과 정리(Layer A) sh 의 label — Jenkinsfile_portal sePreserveGatherOutput() 과 같은 글자 (8차 R7 에서 바뀌었다)
LAYER_A_LABEL = "결과 정리 (서버마다 결과 한 줄)"
# 수집 실행 sh 의 label — Jenkinsfile_portal seAttemptBody() 와 같은 글자 (9차: 이 step 뒤에 실행 기반 끊김을 흉내 낸다)
GATHER_LABEL = "서버 정보 수집 (ansible-playbook)"

# 모든 시나리오 — Jenkinsfile_harness · harness_verdict.py 와 같은 목록 (scenarios.json 이 정본)
#   2026-10-05 (8차 R3): Tier 2(SE_FINALIZER_BOUNDED) · Script Approval 실측 시나리오(inner_*_timeout · sandbox_probe)를 없앴다 — 안쪽 단계 상한이 없다.
#   8차 R1: gather_limit_preserve 가 운영 Job 의 강제 한계 S3(gatherBudgetForceSec)를 대신한다.
#   9차 (2026-10-06): gather_stage 시나리오 — 운영 함수 seGatherStage 를 짧은 시험 상수로 그대로 실행하고 실행 기반(Runner 대기 · 연결 끊김 ·
#   작업 폴더 사라짐 · 결과 처리 노드 대기)만 wrapper 가 흉내 낸다: gather_limit_preserve · infra_resume · infra_wait_expired · resume_impossible ·
#   gather_wait_abort.
#   10차 (2026-10-07): 결과 처리 재진입(R1) · 기록 파일 일시 읽기 실패(R2) · 첫 준비 끊김 · 접수 목록 복원 · 확정 결과 사라짐(R3) ·
#   마지막 보존 표식(N1) · Add-on 결정 재사용(R4). 장애는 시나리오의 faults(op · 대상 · n번째 호출 · infra|fail)로 넣는다.
SCENARIOS = ("normal_success", "archive_fail", "stash_fail", "both_fail", "truncate_jsonl", "checkpoint_only_a",
             "checkpoint_only_b", "layer_a_fail", "raw_fallback", "report_corrupt", "sink_5xx", "sink_close",
             "recover_slow", "outer_timeout", "foreign_timeout_interruption",
             "user_abort", "aborted_outcome_finalize", "sink_hold",
             "archive_slow", "layer_a_read_slow", "gather_limit_preserve",
             "infra_resume", "infra_wait_expired", "resume_impossible", "gather_wait_abort",
             "finalize_reentry", "finalize_reentry_after_delivery", "finalize_reentry_expired", "finalize_reentry_abort",
             "finalize_refused_no_resend",
             "finalize_limit_cumulative", "owner_read_transient", "run_record_read_transient", "prep_cut_after_owner",
             "prep_cut_after_cleanup", "prep_cut_after_manifest", "manifest_missing_restore", "results_missing_refuse",
             "preserve_archive_ok_stash_fail", "preserve_stash_ok_archive_fail", "preserve_both_fail", "preserve_cut_before_marker",
             "preserve_cut_delete", "preserve_cut_owner_write", "addon_decision_transient", "addon_reuse_disabled", "addon_copy_restore")

WRAPPERS = r'''

// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
// harness wrappers (generated by tests/jenkins/harness/build_functions.py — NOT part of the runtime pipeline)
//   scenario: __SCENARIO__
//   스크립트 메서드는 같은 이름의 DSL step 보다 먼저 해석된다. 실제 step 은 HARNESS.outer(바깥 WorkflowScript)로 위임한다.
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
// 타입 없는 대입 = 스크립트 binding 변수 — 메서드에서 보인다 (typed 선언은 run() 의 지역변수가 돼 MissingPropertyException, Harness #5 실측)
HARNESS = [scenario: '__SCENARIO__', calls: [], params: [:], trusted: [:], outer: null, slowDone: false, gather: null,
           nodeCalls: 0, gatherCalls: 0, builtinCalls: 0, offline: false, agentLost: false, removeWs: false, wsPath: null,
           faults: [], opCounts: [:], slow: [:], finalizeDelays: null, hooks: [:]]

def seHarnessInit(Object outer, Map cfg) {
    HARNESS.outer = outer
    HARNESS.params = (cfg.params ?: [:])
    HARNESS.trusted = (cfg.trusted ?: [:])
    HARNESS.slowSeconds = (cfg.slowSeconds ?: 45) as int
    HARNESS.calls = []
    HARNESS.gather = cfg.gather      // 9차 gather_stage 시나리오만 — 그 외에는 null(아래 wrapper 가 실제 step 으로 그대로 넘긴다)
    HARNESS.faults = (cfg.faults ?: [])             // 10차: [{op, match, nth, kind: infra | fail}] — op(대상)의 n번째 호출에서
    HARNESS.slow = (cfg.slow ?: [:])                // 10차: {op: 초} — 그 step 을 호출마다 늦춘다
    HARNESS.finalizeDelays = cfg.finalizeDelays     // 10차: 결과 처리 노드(built-in)를 얻기까지 늦출 초 — 진입마다(마지막 값을 이어 쓴다)
    HARNESS.opCounts = [:]
    return this
}

// 10차: 장애 주입 — op(대상)의 n번째 호출에서 일으킨다. infra 는 실행 기반 오류 흉내(Runner 오프라인으로 두고 retry(agent()) 가 본문을 다시 부르게 한다),
//   fail 은 보통 실패(보존 단계 독립 시험). 운영 함수는 그대로다 — 주입은 이 wrapper 들에만 있다.
def seHarnessFault(String op, String target) {
    String key = op + ':' + (target ?: '')
    int n = ((HARNESS.opCounts[key] ?: 0) as int) + 1
    HARNESS.opCounts[key] = n
    for (Map f in HARNESS.faults) {
        if (f.op == op && ((f.match ?: '') == (target ?: '')) && ((f.nth ?: 1) as int) == n) {
            String kind = (f.kind ?: 'infra')
            HARNESS.calls << ('fault:' + kind + ':' + key + '#' + n)
            if (kind == 'infra') {
                HARNESS.agentLost = true
                HARNESS.offline = true
                throw new Exception('harness: injected infrastructure failure at ' + key + ' #' + n)
            }
            throw new Exception('harness: injected failure at ' + key + ' #' + n)
        }
    }
}

def seHarnessSlow(String op) {
    int sec = (HARNESS.slow[op] ?: 0) as int
    if (sec > 0) {
        HARNESS.calls << ('slow:' + op + ':' + sec)
        HARNESS.outer.sleep(time: sec, unit: 'SECONDS')
    }
}

def seHarnessState() { return [ws_path: HARNESS.wsPath, node_calls: HARNESS.nodeCalls, gather_calls: HARNESS.gatherCalls] }

// params 그림자 — 함수 본문의 params.loc / params.callbackUrl … 가 Harness 가 준 값을 읽는다 (운영 함수는 손대지 않는다)
def getParams() { return HARNESS.params }

def seHarnessCalls() { return HARNESS.calls }

def archiveArtifacts(Map m) {
    // 주입 대상은 Gather post 의 보존 archive(gather_output.json 으로 시작하는 목록)뿐 — finalizer 의 callback_body/summary archive 는 실제로 보낸다
    if ((HARNESS.scenario in __SLOW_ARCHIVE__) && (m.artifacts ?: '').toString().startsWith('gather_output.json')) {
        HARNESS.calls << ("archiveArtifacts:slow:" + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    if ((HARNESS.scenario in __FAIL_ARCHIVE__) && (m.artifacts ?: '').toString().startsWith('gather_output.json')) {
        HARNESS.calls << 'archiveArtifacts:injected_fail'
        throw new Exception('harness: injected archiveArtifacts failure')
    }
    seHarnessFault('archiveArtifacts', (m.artifacts ?: '').toString().split(',')[0])
    HARNESS.calls << 'archiveArtifacts'
    return HARNESS.outer.archiveArtifacts(m)
}

def stash(Map m) {
    if ((HARNESS.scenario in __FAIL_STASH__) && m.name == 'gather-output') {
        HARNESS.calls << 'stash:injected_fail'
        throw new Exception('harness: injected stash failure')
    }
    seHarnessFault('stash', (m.name ?: '').toString())
    HARNESS.calls << 'stash'
    return HARNESS.outer.stash(m)
}

def unstash(String name) {
    if (HARNESS.scenario in __SLOW_UNSTASH__) {
        HARNESS.calls << ("unstash:slow:" + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    if (HARNESS.scenario in __FOREIGN_TIMEOUT_UNSTASH__) {
        // 다른 timeout step(이 wrapper 의 것)이 만든 ExceededTimeout — 결과 확인 및 전송 단계는 어떤 interruption 도 삼키지 않고 재전파해야 한다
        HARNESS.calls << 'unstash:foreign_timeout'
        HARNESS.outer.timeout(time: 2, unit: 'SECONDS') { HARNESS.outer.sleep(time: 30, unit: 'SECONDS') }
    }
    seHarnessSlow('unstash')
    seHarnessFault('unstash', name)
    HARNESS.calls << 'unstash'
    return HARNESS.outer.unstash(name)
}

def unarchive(Map m) {
    HARNESS.calls << 'unarchive'
    return HARNESS.outer.unarchive(m)
}

// 생성 tree 검증(FUNCTIONS_SRC=artifact)에서는 readTrusted 가 main 이 아니라 그 tree 의 helper 를 돌려줘야 한다 → trusted 매핑
def readTrusted(String path) {
    if (HARNESS.scenario in __FAIL_READTRUSTED__) {
        HARNESS.calls << ('readTrusted:injected_fail:' + path)
        throw new Exception('harness: injected readTrusted failure for ' + path)
    }
    HARNESS.calls << ('readTrusted:' + path)
    if (HARNESS.trusted.containsKey(path)) {
        return HARNESS.trusted[path]      // 생성 tree 의 파일 **내용**(Harness 가 agent 에서 미리 읽어 둔다 — finalizer 는 built-in node 에서 돈다)
    }
    return HARNESS.outer.readTrusted(path)
}

// 결과 확인 단계의 정리 결과 읽기(readFile gather_final.jsonl)만 늦춘다 — 안쪽 상한 없이 기다려 완주하는지 본다 (최종 지시 §4-3 · 8차 R3)
def readFile(Map m) {
    if ((HARNESS.scenario in __SLOW_READFILE_FINAL__) && (m.file ?: '').toString() == 'gather_final.jsonl' && !HARNESS.slowDone) {
        HARNESS.slowDone = true
        HARNESS.calls << ('readFile:slow:' + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    seHarnessFault('readFile', (m.file ?: '').toString())
    HARNESS.calls << ('readFile:' + (m.file ?: '-'))
    return HARNESS.outer.readFile(m)
}

// 10차: 기록 파일 쓰기 · 존재 확인 · 폴더 삭제 — 장애 주입 지점(재진입 · 준비 끊김 · 보존 뒤 끊김)
def writeFile(Map m) {
    seHarnessFault('writeFile', (m.file ?: '').toString())
    HARNESS.calls << ('writeFile:' + (m.file ?: '-'))
    return HARNESS.outer.writeFile(m)
}

def fileExists(String f) {
    seHarnessFault('fileExists', f)
    return HARNESS.outer.fileExists(f)
}

def deleteDir() {
    seHarnessFault('deleteDir', '')
    HARNESS.calls << 'deleteDir'
    return HARNESS.outer.deleteDir()
}

def sh(Map m) {
    if ((HARNESS.scenario in __FAIL_LAYER_A__) && m.label == '__LAYER_A_LABEL__') {
        HARNESS.calls << 'sh:layerA:injected_rc1'
        return 1
    }
    seHarnessFault('sh', (m.label ?: '-').toString())
    HARNESS.calls << ('sh:' + (m.label ?: '-'))
    def res = HARNESS.outer.sh(m)
    if (HARNESS.gather != null && m.label == '__GATHER_LABEL__') {
        // 9차: 가짜 ansible 이 계획대로 수집 셸을 끝 기록 없이 끝냈다(crash). 계획이 agent_lost 면 Runner 를 오프라인으로 두고, Jenkins 가 끊긴
        //   Runner 의 step 을 끝낼 때처럼 실제 interruption(다른 timeout 의 FlowInterruptedException)을 만든다 — 운영 함수의 catch 경로를 그대로 탄다
        int k = HARNESS.gatherCalls as int
        HARNESS.gatherCalls = k + 1
        Map step = (k < HARNESS.gather.attempts.size()) ? HARNESS.gather.attempts[k] : [:]
        HARNESS.calls << ('gather:attempt:' + (k + 1) + ':rc:' + res)
        if (step.agent_lost == true) {
            HARNESS.offline = true
            HARNESS.agentLost = true
            HARNESS.calls << ('gather:agent_lost:' + (k + 1))
            HARNESS.outer.timeout(time: 1, unit: 'SECONDS') { HARNESS.outer.sleep(time: 30, unit: 'SECONDS') }
        }
    }
    return res
}

// ── 9차 gather_stage: 실행 기반을 흉내 낸다. gather 가 없는 시나리오는 모두 실제 step 으로 그대로 넘긴다.
//    node(): 결과 처리 노드(built-in)는 실제 node 로(계획한 만큼 늦게), 수집 라벨 · Runner 는 이 Harness 가 이미 잡은 executor 안에서 실행한다
//            (운영 Runner 의 executor 를 더 잡지 않는다). 계획(attempts[k].queue_delay)만큼 기다린 뒤 실행 — 그동안 운영 함수의 대기 한도가 실제로 돈다.
def node(String target, Closure body) {
    if (target == 'built-in' && (HARNESS.gather != null || HARNESS.finalizeDelays != null)) {
        // 결과 처리 노드 — 진입마다 계획한 만큼 늦게(10차: 재진입 대기 · 대기 한도 초과 · 대기 중 취소 시험)
        int b = HARNESS.builtinCalls as int
        HARNESS.builtinCalls = b + 1
        List fds = HARNESS.finalizeDelays
        int fd = (fds != null && !fds.isEmpty()) ? (((b < fds.size()) ? fds[b] : fds[fds.size() - 1]) ?: 0) as int : ((HARNESS.gather?.finalize_delay ?: 0) as int)
        HARNESS.calls << ('node:built-in:delay:' + fd)
        if (fd > 0) { HARNESS.outer.sleep(time: fd, unit: 'SECONDS') }
        return HARNESS.outer.node('built-in') { body() }
    }
    if (HARNESS.gather == null) { return HARNESS.outer.node(target) { body() } }
    int k = HARNESS.nodeCalls as int
    HARNESS.nodeCalls = k + 1
    // 시도마다의 노드 단계(대기 · 폴더 사라짐 · 파일 지우기 · Add-on ref 옮기기) — node_steps 가 있으면 그것을, 없으면 attempts 를 쓴다(9차 시나리오)
    List steps = (HARNESS.gather.node_steps != null) ? HARNESS.gather.node_steps : HARNESS.gather.attempts
    Map step = (k < steps.size()) ? steps[k] : [:]
    int d = (step.queue_delay ?: 0) as int
    HARNESS.calls << ('node:' + target + ':delay:' + d)
    if (d > 0) { HARNESS.outer.sleep(time: d, unit: 'SECONDS') }
    HARNESS.offline = false
    HARNESS.removeWs = (step.remove_workspace == true)
    HARNESS.hooks = step
    return body()
}

// 등록 · 연결 상태 — 흉내 낸 끊김 동안만 오프라인. deregistered 면 등록된 Runner 가 없다
def nodesByLabel(Map m) {
    if (HARNESS.gather == null) { return HARNESS.outer.nodesByLabel(m) }
    HARNESS.calls << ('nodesByLabel:' + (m.offline == true ? 'registered' : 'online') + ':' + (HARNESS.offline ? 'offline' : 'on'))
    if (m.offline == true) { return (HARNESS.gather.deregistered == true) ? [] : [m.label] }
    return HARNESS.offline ? [] : [m.label]
}

// retry(agent() 조건) — Jenkins 가 끊긴 Runner 의 step 을 끝내면 retry 가 본문을 한 번 더 부른다(2026-10-06 se-probe 실측). 흉내 낸 끊김일 때만 그렇게 한다.
def retry(Map m, Closure body) {
    if (m.conditions == null || (HARNESS.gather == null && !HARNESS.faults)) { return HARNESS.outer.retry(m) { body() } }
    int count = (m.count ?: 1) as int
    for (int i = 1; i <= count; i++) {
        try {
            return body()
        } catch (Throwable t) {
            if (HARNESS.agentLost == true && i < count) {
                HARNESS.agentLost = false
                HARNESS.calls << 'retry:agent_lost'
                continue
            }
            throw t
        }
    }
    return null
}

// 작업 폴더 — 실제 ws 다(이 Runner 의 <agent root>/<Job>-<번호>). 계획이 remove_workspace 면 그 시도 전에 폴더를 지운다(끊긴 사이 폴더가 사라짐)
def ws(String path, Closure body) {
    if (HARNESS.gather == null) { return HARNESS.outer.ws(path) { body() } }
    return HARNESS.outer.ws(path) {
        HARNESS.wsPath = HARNESS.outer.pwd()
        if (HARNESS.removeWs == true) {
            HARNESS.removeWs = false
            HARNESS.calls << 'ws:removed'
            HARNESS.outer.deleteDir()
        }
        // 10차: 시도 사이의 변화 — 파일 하나 사라짐(접수 목록 · 결과 파일) · Add-on 사본 사라짐 · Add-on 저장소의 ref 가 바뀜
        Map hk = (HARNESS.hooks ?: [:])
        HARNESS.hooks = [:]
        for (Object f in (hk.remove_files ?: [])) {
            HARNESS.calls << ('ws:remove:' + f)
            HARNESS.outer.sh(label: 'harness: 파일 지우기', script: "rm -rf '" + f + "'")
        }
        if (hk.remove_addon_copy == true) {
            HARNESS.calls << 'ws:remove:addon'
            HARNESS.outer.sh(label: 'harness: Add-on 사본 지우기', script: 'rm -rf addon')
        }
        if (hk.addon_ref_to) {
            Map ad = (HARNESS.gather.addon ?: [:])
            HARNESS.calls << ('addon:ref:' + hk.addon_ref_to)
            HARNESS.outer.sh(label: 'harness: Add-on ref 옮기기', script: "git -C '" + ad.bare + "' update-ref refs/heads/main " + ad.commits[hk.addon_ref_to])
        }
        body()
    }
}

// 저장소 받기 — 시험 사본(gather_ws: scripts · common · <채널>-gather 자리)을 복사한다. 운영 Job 의 SCM 을 다시 받지 않는다
def getScm() { return 'harness-scm' }

def checkout(Object s) {
    if (HARNESS.gather == null) { return HARNESS.outer.checkout(HARNESS.outer.scm) }
    HARNESS.calls << 'checkout:copy'
    HARNESS.outer.sh(label: 'harness: 저장소 사본', script: "cp -a '" + HARNESS.gather.src + "/.' .")
    return [GIT_COMMIT: HARNESS.gather.sha]
}

// vault 비밀번호 — 가짜 ansible 은 읽지 않는다. 실제 credential 을 꺼내지 않는다
def withCredentials(List creds, Closure body) {
    if (HARNESS.gather == null) { return HARNESS.outer.withCredentials(creds) { body() } }
    HARNESS.calls << 'withCredentials:stub'
    return HARNESS.outer.withEnv(['VAULT_PASSWORD=harness-stub']) { body() }
}

// 결과는 verdict 가 정한다 — 함수가 부른 unstable() 은 기록만 한다 (Jenkins 결과를 바꾸지 않으므로 한 빌드 안의 시나리오를 오염시키지 않는다)
def unstable(String msg) {
    HARNESS.calls << ('unstable:' + msg)
}

def httpRequest(Map m) {
    HARNESS.calls << ('httpRequest:' + m.url)
    return HARNESS.outer.httpRequest(m)
}

return this
'''


def extract_functions(source_text: str) -> str:
    """`pipeline {` 앞의 최상위 선언부. 열 0 의 `pipeline {` 만 경계로 본다."""
    m = re.search(r"^pipeline \{\s*$", source_text, re.M)
    if not m:
        raise SystemExit("source has no top-level 'pipeline {' — not a Jenkinsfile_portal")
    return source_text[: m.start()]


def groovy_list(names: set[str]) -> str:
    return "[" + ", ".join(f"'{n}'" for n in sorted(names)) + "]"


def build(source: Path, scenario: str, out: Path, meta_out: Path | None) -> dict:
    if scenario not in SCENARIOS:
        raise SystemExit(f"unknown scenario {scenario!r} — one of {SCENARIOS}")
    raw = source.read_bytes()
    text = raw.decode("utf-8")
    functions = extract_functions(text)
    for required in ("def seFinalizeAndCallback()", "def sePreserveGatherOutput()", "Map seConstants()", "def seGatherStage(", "def seWithNode(",
                     "Map seOutcomeFromState(", "Map seReadGatherRun()"):
        if required not in functions:
            raise SystemExit(f"source functions block lacks {required!r}")
    for label in (LAYER_A_LABEL, GATHER_LABEL):
        if f"label: '{label}'" not in functions:
            raise SystemExit(f"source functions block has no sh labelled {label!r} — the fault injection would not apply")
    if "return this" in functions:
        raise SystemExit("source functions block already contains 'return this' — unexpected")
    wrappers = (WRAPPERS.replace("__SCENARIO__", scenario)
                .replace("__FAIL_ARCHIVE__", groovy_list(FAIL_ARCHIVE))
                .replace("__FAIL_STASH__", groovy_list(FAIL_STASH))
                .replace("__FAIL_LAYER_A__", groovy_list(FAIL_LAYER_A))
                .replace("__FAIL_READTRUSTED__", groovy_list(FAIL_READTRUSTED))
                .replace("__SLOW_UNSTASH__", groovy_list(SLOW_UNSTASH))
                .replace("__FOREIGN_TIMEOUT_UNSTASH__", groovy_list(FOREIGN_TIMEOUT_UNSTASH))
                .replace("__SLOW_ARCHIVE__", groovy_list(SLOW_ARCHIVE))
                .replace("__SLOW_READFILE_FINAL__", groovy_list(SLOW_READFILE_FINAL))
                .replace("__LAYER_A_LABEL__", LAYER_A_LABEL)
                .replace("__GATHER_LABEL__", GATHER_LABEL))
    generated = functions.rstrip("\n") + "\n" + wrappers
    _write_lf(out, generated)
    meta = {
        "scenario": scenario,
        "source": str(source),
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "functions_sha256": hashlib.sha256(functions.encode("utf-8")).hexdigest(),
        "functions_lines": functions.count("\n"),
        "defs": re.findall(r"^(?:def|Map|boolean|long|List|String) (se\w+)\(", functions, re.M),
    }
    if meta_out:
        _write_lf(meta_out, json.dumps(meta, ensure_ascii=False, indent=2))
    return meta


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--source", required=True, help="Jenkinsfile_portal (main checkout 또는 생성 tree 사본)")
    ap.add_argument("--scenario", required=True, choices=SCENARIOS)
    ap.add_argument("--out", required=True)
    ap.add_argument("--meta", default="")
    a = ap.parse_args(argv)
    meta = build(Path(a.source), a.scenario, Path(a.out), Path(a.meta) if a.meta else None)
    sys.stdout.write(json.dumps(meta, ensure_ascii=False) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
