#!/usr/bin/env python3
"""build_functions.py — Jenkinsfile_portal 의 최상위 함수들을 떼어 Harness 용 Groovy 스크립트를 만든다 (2026-10-04, Astra 3차 §5-2).

운영 코드에는 장애 주입 분기를 넣지 않는다. 대신 이 도구가
  1. Jenkinsfile_portal(main checkout 또는 생성 tree 의 사본) 에서 `pipeline {` 앞의 최상위 선언(상수·helper·seFinalizeAndCallback·
     sePreserveGatherOutput …)을 **그대로** 잘라내고,
  2. 같은 이름의 **wrapper 메서드**(archiveArtifacts · stash · unstash · unarchive · readTrusted · readFile · sh · unstable · httpRequest) 와
     `getParams()`(params 그림자) 를 덧붙여 — 스크립트 메서드가 DSL step 보다 먼저 해석되므로 시나리오별로 실제 step 에 위임하거나
     예외·지연을 일으킨다 —
  3. `return this` 로 끝나는 파일을 만든다. Jenkinsfile_harness 가 `load` 한 뒤 `seHarnessInit(this, cfg)` 로 바깥 스크립트(실제 step)를 넘긴다.

원본 함수 본문은 글자 하나 바꾸지 않는다 — 출력의 `source_sha256`(원본 파일 해시)과 `functions_sha256`(잘라낸 부분 해시)를 기록해
어느 생성물의 함수를 검증했는지 남긴다 (wrapper 를 붙이기 전 해시).

사용:
  python3 tests/jenkins/harness/build_functions.py --source Jenkinsfile_portal --scenario archive_fail \
      --out harness_functions.groovy --meta harness_functions_meta.json
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


def _write_lf(path, text):
    """LF 고정 쓰기 — Path.write_text(newline=) 는 Python 3.10+ 라 Runner 시스템 python3(3.9) 에서 못 쓴다."""
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

FAIL_ARCHIVE = {"archive_fail", "both_fail"}
FAIL_STASH = {"stash_fail", "both_fail"}
FAIL_LAYER_A = {"layer_a_fail", "checkpoint_only_b"}
FAIL_READTRUSTED = {"raw_fallback"}
SLOW_UNSTASH = {"recover_slow", "outer_timeout", "user_abort"}
FOREIGN_TIMEOUT_UNSTASH = {"foreign_timeout_interruption"}    # unstash 안에서 **다른** timeout 으로 FIE 를 만든다 (3차 §4 ⑥)
# 2026-10-04 최종 지시 §4-3 — 느린 보존 archive / 결과 확인 단계의 정리 결과 읽기(readFile gather_final.jsonl). 8차 R3: 안쪽 상한이 없어 기다려 완주한다
SLOW_ARCHIVE = {"archive_slow"}
SLOW_READFILE_FINAL = {"layer_a_read_slow"}
# 결과 정리(Layer A) sh 의 label — Jenkinsfile_portal sePreserveGatherOutput() 과 같은 글자 (8차 R7 에서 바뀌었다)
LAYER_A_LABEL = "결과 정리 (서버마다 결과 한 줄)"

# 모든 시나리오 — Jenkinsfile_harness · harness_verdict.py 와 같은 목록 (scenarios.json 이 정본)
#   2026-10-05 (8차 R3): Tier 2(SE_FINALIZER_BOUNDED) · Script Approval 실측 시나리오(inner_*_timeout · sandbox_probe)를 없앴다 — 안쪽 단계 상한이 없다.
#   8차 R1: gather_limit_preserve 가 운영 Job 의 강제 한계 S3(gatherBudgetForceSec)를 대신한다.
SCENARIOS = ("normal_success", "archive_fail", "stash_fail", "both_fail", "truncate_jsonl", "checkpoint_only_a",
             "checkpoint_only_b", "layer_a_fail", "raw_fallback", "report_corrupt", "sink_5xx", "sink_close",
             "recover_slow", "outer_timeout", "foreign_timeout_interruption",
             "user_abort", "aborted_outcome_finalize", "sink_hold",
             "archive_slow", "layer_a_read_slow", "gather_limit_preserve")

WRAPPERS = r'''

// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
// harness wrappers (generated by tests/jenkins/harness/build_functions.py — NOT part of the runtime pipeline)
//   scenario: __SCENARIO__
//   스크립트 메서드는 같은 이름의 DSL step 보다 먼저 해석된다. 실제 step 은 HARNESS.outer(바깥 WorkflowScript)로 위임한다.
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
// 타입 없는 대입 = 스크립트 binding 변수 — 메서드에서 보인다 (typed 선언은 run() 의 지역변수가 돼 MissingPropertyException, Harness #5 실측)
HARNESS = [scenario: '__SCENARIO__', calls: [], params: [:], trusted: [:], outer: null, slowDone: false]

def seHarnessInit(Object outer, Map cfg) {
    HARNESS.outer = outer
    HARNESS.params = (cfg.params ?: [:])
    HARNESS.trusted = (cfg.trusted ?: [:])
    HARNESS.slowSeconds = (cfg.slowSeconds ?: 45) as int
    HARNESS.calls = []
    return this
}

// params 그림자 — 함수 본문의 params.loc / params.callbackUrl … 가 Harness 가 준 값을 읽는다 (운영 함수는 손대지 않는다)
def getParams() { return HARNESS.params }

def seHarnessCalls() { return HARNESS.calls }

def archiveArtifacts(Map m) {
    // 주입 대상은 Gather post 의 보존 archive(gather_output.json 으로 시작하는 목록)뿐 — finalizer 의 callback_body/summary archive 는 실제로 보낸다
    if ((HARNESS.scenario in __SLOW_ARCHIVE__) && (m.artifacts ?: '').toString().startsWith('gather_output.json')) {
        HARNESS.calls << ("archiveArtifacts:slow:" + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    if ((HARNESS.scenario in __FAIL_ARCHIVE__) && (m.artifacts ?: '').toString().startsWith('gather_output.json')) {
        HARNESS.calls << 'archiveArtifacts:injected_fail'
        throw new Exception('harness: injected archiveArtifacts failure')
    }
    HARNESS.calls << 'archiveArtifacts'
    return HARNESS.outer.archiveArtifacts(m)
}

def stash(Map m) {
    if ((HARNESS.scenario in __FAIL_STASH__) && m.name == 'gather-output') {
        HARNESS.calls << 'stash:injected_fail'
        throw new Exception('harness: injected stash failure')
    }
    HARNESS.calls << 'stash'
    return HARNESS.outer.stash(m)
}

def unstash(String name) {
    if (HARNESS.scenario in __SLOW_UNSTASH__) {
        HARNESS.calls << ("unstash:slow:" + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    if (HARNESS.scenario in __FOREIGN_TIMEOUT_UNSTASH__) {
        // 다른 timeout step(이 wrapper 의 것)이 만든 ExceededTimeout — 결과 확인 및 전송 단계는 어떤 interruption 도 삼키지 않고 재전파해야 한다
        HARNESS.calls << 'unstash:foreign_timeout'
        HARNESS.outer.timeout(time: 2, unit: 'SECONDS') { HARNESS.outer.sleep(time: 30, unit: 'SECONDS') }
    }
    HARNESS.calls << 'unstash'
    return HARNESS.outer.unstash(name)
}

def unarchive(Map m) {
    HARNESS.calls << 'unarchive'
    return HARNESS.outer.unarchive(m)
}

// 생성 tree 검증(FUNCTIONS_SRC=artifact)에서는 readTrusted 가 main 이 아니라 그 tree 의 helper 를 돌려줘야 한다 → trusted 매핑
def readTrusted(String path) {
    if (HARNESS.scenario in __FAIL_READTRUSTED__) {
        HARNESS.calls << ('readTrusted:injected_fail:' + path)
        throw new Exception('harness: injected readTrusted failure for ' + path)
    }
    HARNESS.calls << ('readTrusted:' + path)
    if (HARNESS.trusted.containsKey(path)) {
        return HARNESS.trusted[path]      // 생성 tree 의 파일 **내용**(Harness 가 agent 에서 미리 읽어 둔다 — finalizer 는 built-in node 에서 돈다)
    }
    return HARNESS.outer.readTrusted(path)
}

// 결과 확인 단계의 정리 결과 읽기(readFile gather_final.jsonl)만 늦춘다 — 안쪽 상한 없이 기다려 완주하는지 본다 (최종 지시 §4-3 · 8차 R3)
def readFile(Map m) {
    if ((HARNESS.scenario in __SLOW_READFILE_FINAL__) && (m.file ?: '').toString() == 'gather_final.jsonl' && !HARNESS.slowDone) {
        HARNESS.slowDone = true
        HARNESS.calls << ('readFile:slow:' + HARNESS.slowSeconds)
        HARNESS.outer.sleep(time: HARNESS.slowSeconds, unit: 'SECONDS')
    }
    HARNESS.calls << ('readFile:' + (m.file ?: '-'))
    return HARNESS.outer.readFile(m)
}

def sh(Map m) {
    if ((HARNESS.scenario in __FAIL_LAYER_A__) && m.label == '__LAYER_A_LABEL__') {
        HARNESS.calls << 'sh:layerA:injected_rc1'
        return 1
    }
    HARNESS.calls << ('sh:' + (m.label ?: '-'))
    return HARNESS.outer.sh(m)
}

// 결과는 verdict 가 정한다 — 함수가 부른 unstable() 은 기록만 한다 (Jenkins 결과를 바꾸지 않으므로 한 빌드 안의 시나리오를 오염시키지 않는다)
def unstable(String msg) {
    HARNESS.calls << ('unstable:' + msg)
}

def httpRequest(Map m) {
    HARNESS.calls << ('httpRequest:' + m.url)
    return HARNESS.outer.httpRequest(m)
}

return this
'''


def extract_functions(source_text: str) -> str:
    """`pipeline {` 앞의 최상위 선언부. 열 0 의 `pipeline {` 만 경계로 본다."""
    m = re.search(r"^pipeline \{\s*$", source_text, re.M)
    if not m:
        raise SystemExit("source has no top-level 'pipeline {' — not a Jenkinsfile_portal")
    return source_text[: m.start()]


def groovy_list(names: set[str]) -> str:
    return "[" + ", ".join(f"'{n}'" for n in sorted(names)) + "]"


def build(source: Path, scenario: str, out: Path, meta_out: Path | None) -> dict:
    if scenario not in SCENARIOS:
        raise SystemExit(f"unknown scenario {scenario!r} — one of {SCENARIOS}")
    raw = source.read_bytes()
    text = raw.decode("utf-8")
    functions = extract_functions(text)
    for required in ("def seFinalizeAndCallback()", "def sePreserveGatherOutput()", "Map seConstants()", "Map seGatherOutcome(", "Map seReadGatherRun()"):
        if required not in functions:
            raise SystemExit(f"source functions block lacks {required!r}")
    if f"label: '{LAYER_A_LABEL}'" not in functions:
        raise SystemExit(f"source functions block has no sh labelled {LAYER_A_LABEL!r} — the Layer A fault injection would not apply")
    if "return this" in functions:
        raise SystemExit("source functions block already contains 'return this' — unexpected")
    wrappers = (WRAPPERS.replace("__SCENARIO__", scenario)
                .replace("__FAIL_ARCHIVE__", groovy_list(FAIL_ARCHIVE))
                .replace("__FAIL_STASH__", groovy_list(FAIL_STASH))
                .replace("__FAIL_LAYER_A__", groovy_list(FAIL_LAYER_A))
                .replace("__FAIL_READTRUSTED__", groovy_list(FAIL_READTRUSTED))
                .replace("__SLOW_UNSTASH__", groovy_list(SLOW_UNSTASH))
                .replace("__FOREIGN_TIMEOUT_UNSTASH__", groovy_list(FOREIGN_TIMEOUT_UNSTASH))
                .replace("__SLOW_ARCHIVE__", groovy_list(SLOW_ARCHIVE))
                .replace("__SLOW_READFILE_FINAL__", groovy_list(SLOW_READFILE_FINAL))
                .replace("__LAYER_A_LABEL__", LAYER_A_LABEL))
    generated = functions.rstrip("\n") + "\n" + wrappers
    _write_lf(out, generated)
    meta = {
        "scenario": scenario,
        "source": str(source),
        "source_sha256": hashlib.sha256(raw).hexdigest(),
        "functions_sha256": hashlib.sha256(functions.encode("utf-8")).hexdigest(),
        "functions_lines": functions.count("\n"),
        "defs": re.findall(r"^(?:def|Map|boolean|long|List|String) (se\w+)\(", functions, re.M),
    }
    if meta_out:
        _write_lf(meta_out, json.dumps(meta, ensure_ascii=False, indent=2))
    return meta


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--source", required=True, help="Jenkinsfile_portal (main checkout 또는 생성 tree 사본)")
    ap.add_argument("--scenario", required=True, choices=SCENARIOS)
    ap.add_argument("--out", required=True)
    ap.add_argument("--meta", default="")
    a = ap.parse_args(argv)
    meta = build(Path(a.source), a.scenario, Path(a.out), Path(a.meta) if a.meta else None)
    sys.stdout.write(json.dumps(meta, ensure_ascii=False) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
